version: "3.3"

services:
  api:
    image: postgrest/postgrest:v6.0.2
    container_name: odisplay-api
    env_file: .env
    restart: always
    depends_on:
      - database
    ports:
      - 4000:3000

  api-overview:
    image: swaggerapi/swagger-ui
    container_name: odisplay-api-overview
    env_file: .env
    depends_on:
      - api
    ports:
      - 4001:8080

  database:
    image: postgres:12.1-alpine
    container_name: odisplay-database
    env_file: .env
    restart: always
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d

  database-manager:
    image: adminer:4.7.5
    container_name: odisplay-database-manager
    env_file: .env
    restart: always
    depends_on:
      - database
    ports:
      - 4002:8080

volumes:
  data: {}
